# Per default the schema of arbitrary context values of an action cannot be
# typed. Actions that need translatability or other features of the config
# system must specify their context value schema explicitly, see examples below.
nestle_contactlab_rules.action.context_values.*:
  type: ignore
  label: Context values

nestle_contactlab_rules.action.context_values.after_create_new_user_action:
  type: mapping
  label: Message action context values
  mapping:
    message:
      type: text
    type:
      type: string
    repeat:
      type: boolean
