cdn_provider: jsdelivr
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://www.demodev1.local/themes/nestle/favicon.ico'
  use_default: true
schemas:
  bootstrap: 8000
  nestle: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://logo.png'
  url: ''
  use_default: false
cdn_jsdelivr_theme: bootstrap
table: ''
